package com.lastweek.sharing.temporary

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF000000)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFFFFF)
internal val onPrimaryContainerLight = Color(0xFF001D34)
internal val secondaryLight = Color(0xFF526070)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFBA1A1A)
internal val onSecondaryContainerLight = Color(0xFF0F1D2A)
internal val tertiaryLight = Color(0xFF695779)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFF0DBFF)
internal val onTertiaryContainerLight = Color(0xFF241532)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFBA1A1A)
internal val onBackgroundLight = Color(0xFF191C20)
internal val surfaceLight = Color(0xFFF8F9FF)
internal val onSurfaceLight = Color(0xFF191C20)
internal val surfaceVariantLight = Color(0xFFDEE3EB)
internal val onSurfaceVariantLight = Color(0xFF42474E)
internal val outlineLight = Color(0xFF73777F)
internal val outlineVariantLight = Color(0xFFC2C7CF)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2D3135)
internal val inverseOnSurfaceLight = Color(0xFFEFF1F6)
internal val inversePrimaryLight = Color(0xFF9DCAFC)
internal val surfaceDimLight = Color(0xFFD8DAE0)
internal val surfaceBrightLight = Color(0xFFF8F9FF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF2F3F9)
internal val surfaceContainerLight = Color(0xFFECEEF4)
internal val surfaceContainerHighLight = Color(0xFFE6E8EE)
internal val surfaceContainerHighestLight = Color(0xFFE0E2E8)